### ISSUE TITLE
Applicable for Synology NVMe cache?

### ISSUE THREAD

**Issue by LETRA** [Slimbook-Team/samsung#1]
Hello. I have two 970 EVO Plus on Synology cache and would like to know if this tool is compatible with DSM systems by logging from ssh or something similar or do I have to make changes in the commands to apply the patch without causing destruction :-)

**Comment by slimbook** [comment]
Hi, in case of 970 EVO Plus (specifically), you should check if update is required, as mentioned here: https://github.com/Slimbook-Team/samsung/issues/2#issuecomment-1580586220
If an update is required, there should not be any trouble but it is advisable to do it from a Live-USB because it is recommended to unmount the disk before updating it.

**Comment by LETRA** [comment]
Thank you very much for the information and the patch. All the best.
